import { DefaultTheme } from 'styled-components';

export const theme: DefaultTheme = {
  colors: {
    primary: {
      main: '#0070f3',
      light: '#3291ff',
      dark: '#a6a6a6',
      contrast: '#ffffff',
    },
    secondary: {
      main: '#9c96a2',
      light: '#9c4ddb',
      dark: '#5c1e9e',
      contrast: '#ffffff',
    },
    background: {
      primary: '#f5f5f5',
      secondary: '#f0f0f0',
      main: '#f5f5f5',
      dark: '#1a1a1a',
      light: '#fafafa',
    },
    text: {
      primary: '#1a1a1a',
      secondary: '#666666',
      muted: '#999999',
      gray: '#4B5563',
      contrast: '#ffffff',
    },
    error: {
      main: '#ff0000',
      light: '#ff3333',
      dark: '#cc0000',
      contrast: '#ffffff',
    },
    success: {
      main: '#0070f3',
      light: '#3291ff',
      dark: '#0050af',
      contrast: '#ffffff',
    },
    warning: {
      main: '#f5a623',
      light: '#f7b955',
      dark: '#c48619',
      contrast: '#ffffff',
    },
    info: {
      main: '#0070f3',
      light: '#3291ff',
      dark: '#0050af',
      contrast: '#ffffff',
    },
    card: {
      background: '#ffffff',
      hover: '#f5f5f5',
    },
  },
  typography: {
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      md: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
      hero: '4rem',
      heroSubtitle: '2rem',
      '5xl': '3rem',
      '6xl': '3.75rem',
      '7xl': '4.5rem',
    },
    fontWeight: {
      normal: 400,
      medium: 500,
      semibold: 600,
      bold: 700,
    },
    lineHeight: {
      none: 1,
      tight: 1.25,
      normal: 1.5,
      relaxed: 1.75,
    },
    letterSpacing: {
      tighter: '-0.05em',
      tight: '-0.025em',
      normal: '0',
      wide: '0.025em',
      wider: '0.05em',
    },
  },
  fonts: {
    body: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    h1: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    heading: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif',
    mono: 'Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  },
  spacing: {
    xs: '0.5rem',
    sm: '1rem',
    md: '1.5rem',
    lg: '2rem',
    xl: '2.5rem',
    '2xl': '3rem',
    '3xl': '4rem',
    '4xl': '6rem',
    '5xl': '8rem',
  },
  borderRadius: {
    none: '0',
    sm: '0.125rem',
    md: '0.25rem',
    lg: '0.5rem',
    full: '9999px',
  },
  shadows: {
    sm: '0 1px 2px 0 rgba(0, 0, 0, 0.05)',
    md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
    lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
  },
  breakpoints: {
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
    '2xl': '1536px',
  },
  transitions: {
    fast: '0.1s',
    normal: '0.2s',
    slow: '0.3s',
  },
  zIndex: {
    hide: -1,
    auto: 'auto',
    base: 0,
    header: 10,
    dropdown: 1000,
    sticky: 1100,
    fixed: 1200,
    modal: 1300,
    popover: 1400,
    toast: 1500,
  },
  layout: {
    maxWidth: '1200px',
    containerPadding: '1rem',
  },
  grid: {
    columns: {
      desktop: 'repeat(12, 1fr)',
      tablet: 'repeat(8, 1fr)',
      mobile: 'repeat(4, 1fr)',
    },
  },
};
