# Temporarily disabled
# name: Branch Protection
# 
# on:
#   pull_request:
#     branches: [main]
#   push:
#     branches: [main]
# 
# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v2
#         with:
#           node-version: '20'
#       - run: npm ci
#       - run: npm run build
#       - run: npm test
# 
#   protect-main:
#     needs: build-and-test
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - name: Protect main branch
#         run: |
#           if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
#             echo "Direct pushes to main branch are not allowed"
#             exit 1
#           fi 